[package]
name = "eugene"
version = "0.1.0"
edition = "2021"
description = "Careful with That Lock, Eugene"

license = "MIT"
authors = ["Robin Kåveland <kaaveland@gmail.com>"]
homepage = "https://github.com/kaaveland/eugene"
repository = "https://github.com/kaaveland/eugene.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.7"
anyhow = "1.0.82"
regex = "1.5.4"
clap = { version = "4.5.4", features = ["derive"]}
