[book]
authors = ["Robin Kåveland"]
language = "en"
multilingual = false
src = "src"
title = "Eugene Documentation"

[output.html]
site-url = "/eugene"
git-repository-url = "https://github.com/kaaveland/eugene"

[output.html.fold]
enable = true
level = 1
