baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'eugene documentation'
theme = "book"

[params]
BookTheme = "auto"
BookRepo = "https://github.com/kaaveland/eugene"
BookComments = false
