name: Build eugene web image main

on:
  push:
    branches:
      - main
      - eugene-web

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Cache Cargo registry
          uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/registry/index
              ~/.cargo/registry/cache
              ~/.cargo/git/db
            key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
            restore-keys: |
              ${{ runner.os }}-cargo-registry-
        - name: Build eugene web release
          run: cargo build --release
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.EUGENE_WEB_GHCR }}
        - name: Build eugene web image
          run: |
            docker build -t ghcr.io/${{ github.repository}}-web:latest \
              -t ghcr.io/${{ github.repository}}-web:$GITHUB_SHA \
              -f eugene-web/Dockerfile .
            docker push ghcr.io/${{ github.repository}}-web:latest
            docker push ghcr.io/${{ github.repository}}-web:$GITHUB_SHA
