name: Tests

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --all -- --check
  check_clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: {os: [ubuntu-latest, macos-latest, windows-latest] }
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --all-targets --all-features
